### ISSUE TITLE
About multiGPUs

### ISSUE THREAD

**Issue by MyHins** [Tungthanhlee/ALASKA2#1]
In need I want to use multiGPUs, but when I try to set MultiGpu = TRUE, i get an error that  "Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! "，That means this code is not allow multiGPUs? Can you tell me how to solve this problem? Thanks

**Comment by Tungthanhlee** [comment]
You should set **CUDA_VISIBLE_DEVICES=0** to **CUDA_VISIBLE_DEVICES=0,1** (assuming that you have GPU 0 and GPU 1, and they are both available) before _python main.py_. Let me know if it solves your problem.

**Comment by MyHins** [comment]
I set multiGPU = TRUE,and use CUDA_VISIBLE_DEVICES=2,3,4,5 python /data1/liyx/tamperClassification/Alaska2_49/ALASKA2-master/main.py to run this code, but it can not solve this problem. Have you tried to use MultiGPUs to run it sucessfully?
I'm trying to find out if there is a definition where only one GPU can be used，but I failed. When I set multiGPU = False,the code can run prefectly by using one GPU.
|
|










At 2022-04-21 15:50:41, "Thanh-Tung Le" ***@***.***> wrote:

You should set CUDA_VISIBLE_DEVICES=0 to CUDA_VISIBLE_DEVICES=0,1 (assuming that you have GPU 0 and GPU 1, and they are both available) before python main.py. Let me know if it solves your problem.

**Comment by MyHins** [comment]
Hi，when I set ”_C.SYSTEM.FP16 = False“ and "SYSTEM.MULTI_GPU = TRUE"， this code can run in MultiGPU sucessfully! So I want to tell you the result, although I do not know why.

**Comment by Tungthanhlee** [comment]
Hi. I think the reason is that my code use amp of [apex](https://github.com/NVIDIA/apex), so it could not run parallel by torch DataParallel. Currently, pytorch has released their [native amp ](https://pytorch.org/docs/stable/amp.html) which supports DataParallel easily, thus I suggest you change the code according to them. Furthermore, If you have time to explore, I recommend you implement DistributedDataParallel, which is much more efficient than the DataParallel but a bit more complicated to implement. Hope that helps.
